name: osu-lazer # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2021.623.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Osu! Lazer # 79 char long summary
description: |
    Click circles

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
    osu-lazer:
        plugin: nil
        source: "https://github.com/snapcore/patchelf"
        build-packages:
        - git
